name: BuildWebApp
on:
  workflow_dispatch:
  pull_request:
    branches:
      - Dev
  push:
    paths-ignore:
      - backend
    branches:
      - Dev

jobs:
  build:
    name: Build Monorepo
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

#       - name: Run prettier
#         run: npm run format-check
#         working-directory: ./frontend

#       - name: Run ESLint
#         run: npm run lint
#         working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Run Tests
        run: npm run test
        working-directory: ./frontend
