name: DeployWebApp
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: self-hosted
    environment:
      name: Production
      url: 'https://openenglishtranslation.bible/'
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build
        run: npm run build
        working-directory: ./frontend
      - name: Reload
        run: pm2 reload open-english-translation
        working-directory: ./frontend


